// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: xeniq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_RegisterProvider_FullMethodName = "/xeniq.ProviderService/RegisterProvider"
	ProviderService_SetAvailability_FullMethodName  = "/xeniq.ProviderService/SetAvailability"
	ProviderService_ListProviders_FullMethodName    = "/xeniq.ProviderService/ListProviders"
	ProviderService_SearchProvider_FullMethodName   = "/xeniq.ProviderService/SearchProvider"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderServiceClient interface {
	// Registers a provider (persists in memory).
	RegisterProvider(ctx context.Context, in *RegisterProviderRequest, opts ...grpc.CallOption) (*RegisterProviderResponse, error)
	// Sets provider availability (Available / Busy / Offline).
	SetAvailability(ctx context.Context, in *SetAvailabilityRequest, opts ...grpc.CallOption) (*SetAvailabilityResponse, error)
	// Consumer calls this to get all available providers.
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	// Consumer calls this to find a provider by code.
	SearchProvider(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) RegisterProvider(ctx context.Context, in *RegisterProviderRequest, opts ...grpc.CallOption) (*RegisterProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_RegisterProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SetAvailability(ctx context.Context, in *SetAvailabilityRequest, opts ...grpc.CallOption) (*SetAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAvailabilityResponse)
	err := c.cc.Invoke(ctx, ProviderService_SetAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SearchProvider(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ProviderService_SearchProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
type ProviderServiceServer interface {
	// Registers a provider (persists in memory).
	RegisterProvider(context.Context, *RegisterProviderRequest) (*RegisterProviderResponse, error)
	// Sets provider availability (Available / Busy / Offline).
	SetAvailability(context.Context, *SetAvailabilityRequest) (*SetAvailabilityResponse, error)
	// Consumer calls this to get all available providers.
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	// Consumer calls this to find a provider by code.
	SearchProvider(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) RegisterProvider(context.Context, *RegisterProviderRequest) (*RegisterProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProvider not implemented")
}
func (UnimplementedProviderServiceServer) SetAvailability(context.Context, *SetAvailabilityRequest) (*SetAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAvailability not implemented")
}
func (UnimplementedProviderServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedProviderServiceServer) SearchProvider(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProvider not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_RegisterProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).RegisterProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_RegisterProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).RegisterProvider(ctx, req.(*RegisterProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SetAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SetAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SetAvailability(ctx, req.(*SetAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SearchProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SearchProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SearchProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SearchProvider(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xeniq.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProvider",
			Handler:    _ProviderService_RegisterProvider_Handler,
		},
		{
			MethodName: "SetAvailability",
			Handler:    _ProviderService_SetAvailability_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _ProviderService_ListProviders_Handler,
		},
		{
			MethodName: "SearchProvider",
			Handler:    _ProviderService_SearchProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xeniq.proto",
}

const (
	ConnectService_StreamIncomingCalls_FullMethodName = "/xeniq.ConnectService/StreamIncomingCalls"
	ConnectService_RequestCall_FullMethodName         = "/xeniq.ConnectService/RequestCall"
	ConnectService_AcceptCall_FullMethodName          = "/xeniq.ConnectService/AcceptCall"
	ConnectService_DeclineCall_FullMethodName         = "/xeniq.ConnectService/DeclineCall"
	ConnectService_StreamConnection_FullMethodName    = "/xeniq.ConnectService/StreamConnection"
)

// ConnectServiceClient is the client API for ConnectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectServiceClient interface {
	// 1. Provider subscribes to incoming calls (Server-Side Stream).
	// Keeps this open to receive "Ringing" events.
	StreamIncomingCalls(ctx context.Context, in *IncomingCallsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingCallEvent], error)
	// 2. Consumer requests a call.
	// Backend checks availability -> Pushes event to Provider -> Returns Call ID.
	RequestCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// 3. Provider accepts the call.
	AcceptCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*AnswerCallResponse, error)
	// 4. Provider declines the call.
	DeclineCall(ctx context.Context, in *DeclineCallRequest, opts ...grpc.CallOption) (*DeclineCallResponse, error)
	// 5. WebRTC Signaling (Offer/Answer/ICE) - Kept for Media Phase.
	StreamConnection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectionEvent, ConnectionEvent], error)
}

type connectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectServiceClient(cc grpc.ClientConnInterface) ConnectServiceClient {
	return &connectServiceClient{cc}
}

func (c *connectServiceClient) StreamIncomingCalls(ctx context.Context, in *IncomingCallsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingCallEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectService_ServiceDesc.Streams[0], ConnectService_StreamIncomingCalls_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IncomingCallsRequest, IncomingCallEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectService_StreamIncomingCallsClient = grpc.ServerStreamingClient[IncomingCallEvent]

func (c *connectServiceClient) RequestCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, ConnectService_RequestCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectServiceClient) AcceptCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*AnswerCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerCallResponse)
	err := c.cc.Invoke(ctx, ConnectService_AcceptCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectServiceClient) DeclineCall(ctx context.Context, in *DeclineCallRequest, opts ...grpc.CallOption) (*DeclineCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineCallResponse)
	err := c.cc.Invoke(ctx, ConnectService_DeclineCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectServiceClient) StreamConnection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectionEvent, ConnectionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectService_ServiceDesc.Streams[1], ConnectService_StreamConnection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectionEvent, ConnectionEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectService_StreamConnectionClient = grpc.BidiStreamingClient[ConnectionEvent, ConnectionEvent]

// ConnectServiceServer is the server API for ConnectService service.
// All implementations must embed UnimplementedConnectServiceServer
// for forward compatibility.
type ConnectServiceServer interface {
	// 1. Provider subscribes to incoming calls (Server-Side Stream).
	// Keeps this open to receive "Ringing" events.
	StreamIncomingCalls(*IncomingCallsRequest, grpc.ServerStreamingServer[IncomingCallEvent]) error
	// 2. Consumer requests a call.
	// Backend checks availability -> Pushes event to Provider -> Returns Call ID.
	RequestCall(context.Context, *CallRequest) (*CallResponse, error)
	// 3. Provider accepts the call.
	AcceptCall(context.Context, *AnswerCallRequest) (*AnswerCallResponse, error)
	// 4. Provider declines the call.
	DeclineCall(context.Context, *DeclineCallRequest) (*DeclineCallResponse, error)
	// 5. WebRTC Signaling (Offer/Answer/ICE) - Kept for Media Phase.
	StreamConnection(grpc.BidiStreamingServer[ConnectionEvent, ConnectionEvent]) error
	mustEmbedUnimplementedConnectServiceServer()
}

// UnimplementedConnectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectServiceServer struct{}

func (UnimplementedConnectServiceServer) StreamIncomingCalls(*IncomingCallsRequest, grpc.ServerStreamingServer[IncomingCallEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamIncomingCalls not implemented")
}
func (UnimplementedConnectServiceServer) RequestCall(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCall not implemented")
}
func (UnimplementedConnectServiceServer) AcceptCall(context.Context, *AnswerCallRequest) (*AnswerCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptCall not implemented")
}
func (UnimplementedConnectServiceServer) DeclineCall(context.Context, *DeclineCallRequest) (*DeclineCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclineCall not implemented")
}
func (UnimplementedConnectServiceServer) StreamConnection(grpc.BidiStreamingServer[ConnectionEvent, ConnectionEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamConnection not implemented")
}
func (UnimplementedConnectServiceServer) mustEmbedUnimplementedConnectServiceServer() {}
func (UnimplementedConnectServiceServer) testEmbeddedByValue()                        {}

// UnsafeConnectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectServiceServer will
// result in compilation errors.
type UnsafeConnectServiceServer interface {
	mustEmbedUnimplementedConnectServiceServer()
}

func RegisterConnectServiceServer(s grpc.ServiceRegistrar, srv ConnectServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectService_ServiceDesc, srv)
}

func _ConnectService_StreamIncomingCalls_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IncomingCallsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectServiceServer).StreamIncomingCalls(m, &grpc.GenericServerStream[IncomingCallsRequest, IncomingCallEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectService_StreamIncomingCallsServer = grpc.ServerStreamingServer[IncomingCallEvent]

func _ConnectService_RequestCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServiceServer).RequestCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectService_RequestCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServiceServer).RequestCall(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectService_AcceptCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServiceServer).AcceptCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectService_AcceptCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServiceServer).AcceptCall(ctx, req.(*AnswerCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectService_DeclineCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServiceServer).DeclineCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectService_DeclineCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServiceServer).DeclineCall(ctx, req.(*DeclineCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectService_StreamConnection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectServiceServer).StreamConnection(&grpc.GenericServerStream[ConnectionEvent, ConnectionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectService_StreamConnectionServer = grpc.BidiStreamingServer[ConnectionEvent, ConnectionEvent]

// ConnectService_ServiceDesc is the grpc.ServiceDesc for ConnectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xeniq.ConnectService",
	HandlerType: (*ConnectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCall",
			Handler:    _ConnectService_RequestCall_Handler,
		},
		{
			MethodName: "AcceptCall",
			Handler:    _ConnectService_AcceptCall_Handler,
		},
		{
			MethodName: "DeclineCall",
			Handler:    _ConnectService_DeclineCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIncomingCalls",
			Handler:       _ConnectService_StreamIncomingCalls_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamConnection",
			Handler:       _ConnectService_StreamConnection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "xeniq.proto",
}

const (
	ControlService_StreamControl_FullMethodName = "/xeniq.ControlService/StreamControl"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	StreamControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEvent, ControlEvent], error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) StreamControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEvent, ControlEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_StreamControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlEvent, ControlEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_StreamControlClient = grpc.BidiStreamingClient[ControlEvent, ControlEvent]

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	StreamControl(grpc.BidiStreamingServer[ControlEvent, ControlEvent]) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) StreamControl(grpc.BidiStreamingServer[ControlEvent, ControlEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamControl not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_StreamControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).StreamControl(&grpc.GenericServerStream[ControlEvent, ControlEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_StreamControlServer = grpc.BidiStreamingServer[ControlEvent, ControlEvent]

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xeniq.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamControl",
			Handler:       _ControlService_StreamControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "xeniq.proto",
}
