// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: xeniq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlModeType int32

const (
	ControlModeType_CONTROL_MODE_BUTTON ControlModeType = 0
	ControlModeType_CONTROL_MODE_GYRO   ControlModeType = 1
)

// Enum value maps for ControlModeType.
var (
	ControlModeType_name = map[int32]string{
		0: "CONTROL_MODE_BUTTON",
		1: "CONTROL_MODE_GYRO",
	}
	ControlModeType_value = map[string]int32{
		"CONTROL_MODE_BUTTON": 0,
		"CONTROL_MODE_GYRO":   1,
	}
)

func (x ControlModeType) Enum() *ControlModeType {
	p := new(ControlModeType)
	*p = x
	return p
}

func (x ControlModeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlModeType) Descriptor() protoreflect.EnumDescriptor {
	return file_xeniq_proto_enumTypes[0].Descriptor()
}

func (ControlModeType) Type() protoreflect.EnumType {
	return &file_xeniq_proto_enumTypes[0]
}

func (x ControlModeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlModeType.Descriptor instead.
func (ControlModeType) EnumDescriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_UNKNOWN          CommandType = 0
	CommandType_ROTATE_LEFT      CommandType = 1
	CommandType_ROTATE_RIGHT     CommandType = 2
	CommandType_MOVE_FORWARD     CommandType = 3
	CommandType_MOVE_BACKWARD    CommandType = 4
	CommandType_POINT_TO_OBJECT  CommandType = 5
	CommandType_ZOOM_IN          CommandType = 6
	CommandType_ZOOM_OUT         CommandType = 7
	CommandType_STOP             CommandType = 8
	CommandType_GYRO_ORIENTATION CommandType = 9
	CommandType_GYRO_RESET       CommandType = 10
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ROTATE_LEFT",
		2:  "ROTATE_RIGHT",
		3:  "MOVE_FORWARD",
		4:  "MOVE_BACKWARD",
		5:  "POINT_TO_OBJECT",
		6:  "ZOOM_IN",
		7:  "ZOOM_OUT",
		8:  "STOP",
		9:  "GYRO_ORIENTATION",
		10: "GYRO_RESET",
	}
	CommandType_value = map[string]int32{
		"UNKNOWN":          0,
		"ROTATE_LEFT":      1,
		"ROTATE_RIGHT":     2,
		"MOVE_FORWARD":     3,
		"MOVE_BACKWARD":    4,
		"POINT_TO_OBJECT":  5,
		"ZOOM_IN":          6,
		"ZOOM_OUT":         7,
		"STOP":             8,
		"GYRO_ORIENTATION": 9,
		"GYRO_RESET":       10,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_xeniq_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_xeniq_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{1}
}

type RegisterProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,2,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderRequest) Reset() {
	*x = RegisterProviderRequest{}
	mi := &file_xeniq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderRequest) ProtoMessage() {}

func (x *RegisterProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterProviderRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RegisterProviderRequest) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *RegisterProviderRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RegisterProviderRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RegisterProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,3,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderResponse) Reset() {
	*x = RegisterProviderResponse{}
	mi := &file_xeniq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderResponse) ProtoMessage() {}

func (x *RegisterProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterProviderResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterProviderResponse) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

type SetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvailabilityRequest) Reset() {
	*x = SetAvailabilityRequest{}
	mi := &file_xeniq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvailabilityRequest) ProtoMessage() {}

func (x *SetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*SetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{2}
}

func (x *SetAvailabilityRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SetAvailabilityRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type SetAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,2,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvailabilityResponse) Reset() {
	*x = SetAvailabilityResponse{}
	mi := &file_xeniq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvailabilityResponse) ProtoMessage() {}

func (x *SetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*SetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{3}
}

func (x *SetAvailabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetAvailabilityResponse) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_xeniq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{4}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderStatusEvent `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_xeniq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{5}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderStatusEvent {
	if x != nil {
		return x.Providers
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderCode  string                 `protobuf:"bytes,1,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_xeniq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,4,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_xeniq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SearchResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type ProviderStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,2,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,3,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"` // True = Available, False = Busy/Offline
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatusEvent) Reset() {
	*x = ProviderStatusEvent{}
	mi := &file_xeniq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatusEvent) ProtoMessage() {}

func (x *ProviderStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatusEvent.ProtoReflect.Descriptor instead.
func (*ProviderStatusEvent) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderStatusEvent) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderStatusEvent) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *ProviderStatusEvent) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *ProviderStatusEvent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ProviderStatusEvent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ProviderStatusEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IncomingCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallsRequest) Reset() {
	*x = IncomingCallsRequest{}
	mi := &file_xeniq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallsRequest) ProtoMessage() {}

func (x *IncomingCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallsRequest.ProtoReflect.Descriptor instead.
func (*IncomingCallsRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{9}
}

func (x *IncomingCallsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type IncomingCallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"` // "Consumer A"
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`                               // "Lost Item"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallEvent) Reset() {
	*x = IncomingCallEvent{}
	mi := &file_xeniq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallEvent) ProtoMessage() {}

func (x *IncomingCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallEvent.ProtoReflect.Descriptor instead.
func (*IncomingCallEvent) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{10}
}

func (x *IncomingCallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IncomingCallEvent) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *IncomingCallEvent) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *IncomingCallEvent) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // Legacy (Optional if code is used, but kept for proto compatibility)
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,5,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"` // NEW: Call by Code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_xeniq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{11}
}

func (x *CallRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CallRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *CallRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *CallRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CallRequest) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_xeniq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{12}
}

func (x *CallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnswerCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCallRequest) Reset() {
	*x = AnswerCallRequest{}
	mi := &file_xeniq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCallRequest) ProtoMessage() {}

func (x *AnswerCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCallRequest.ProtoReflect.Descriptor instead.
func (*AnswerCallRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{13}
}

func (x *AnswerCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AnswerCallRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type AnswerCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCallResponse) Reset() {
	*x = AnswerCallResponse{}
	mi := &file_xeniq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCallResponse) ProtoMessage() {}

func (x *AnswerCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCallResponse.ProtoReflect.Descriptor instead.
func (*AnswerCallResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{14}
}

func (x *AnswerCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnswerCallResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeclineCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineCallRequest) Reset() {
	*x = DeclineCallRequest{}
	mi := &file_xeniq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineCallRequest) ProtoMessage() {}

func (x *DeclineCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineCallRequest.ProtoReflect.Descriptor instead.
func (*DeclineCallRequest) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{15}
}

func (x *DeclineCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DeclineCallRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *DeclineCallRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeclineCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineCallResponse) Reset() {
	*x = DeclineCallResponse{}
	mi := &file_xeniq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineCallResponse) ProtoMessage() {}

func (x *DeclineCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineCallResponse.ProtoReflect.Descriptor instead.
func (*DeclineCallResponse) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{16}
}

func (x *DeclineCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Legacy/WebRTC Signaling Messages
type ConnectionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CallId     string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	SenderId   string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectionEvent_Ice
	//	*ConnectionEvent_Sdp
	//	*ConnectionEvent_End
	Payload       isConnectionEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionEvent) Reset() {
	*x = ConnectionEvent{}
	mi := &file_xeniq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionEvent) ProtoMessage() {}

func (x *ConnectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionEvent.ProtoReflect.Descriptor instead.
func (*ConnectionEvent) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectionEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ConnectionEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ConnectionEvent) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ConnectionEvent) GetPayload() isConnectionEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectionEvent) GetIce() *IceCandidate {
	if x != nil {
		if x, ok := x.Payload.(*ConnectionEvent_Ice); ok {
			return x.Ice
		}
	}
	return nil
}

func (x *ConnectionEvent) GetSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Payload.(*ConnectionEvent_Sdp); ok {
			return x.Sdp
		}
	}
	return nil
}

func (x *ConnectionEvent) GetEnd() *EndCall {
	if x != nil {
		if x, ok := x.Payload.(*ConnectionEvent_End); ok {
			return x.End
		}
	}
	return nil
}

type isConnectionEvent_Payload interface {
	isConnectionEvent_Payload()
}

type ConnectionEvent_Ice struct {
	Ice *IceCandidate `protobuf:"bytes,6,opt,name=ice,proto3,oneof"`
}

type ConnectionEvent_Sdp struct {
	Sdp *SessionDescription `protobuf:"bytes,7,opt,name=sdp,proto3,oneof"`
}

type ConnectionEvent_End struct {
	End *EndCall `protobuf:"bytes,8,opt,name=end,proto3,oneof"`
}

func (*ConnectionEvent_Ice) isConnectionEvent_Payload() {}

func (*ConnectionEvent_Sdp) isConnectionEvent_Payload() {}

func (*ConnectionEvent_End) isConnectionEvent_Payload() {}

type IceCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex int32                  `protobuf:"varint,3,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_xeniq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{18}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

type SessionDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDescription) Reset() {
	*x = SessionDescription{}
	mi := &file_xeniq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDescription) ProtoMessage() {}

func (x *SessionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDescription.ProtoReflect.Descriptor instead.
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{19}
}

func (x *SessionDescription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionDescription) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type EndCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCall) Reset() {
	*x = EndCall{}
	mi := &file_xeniq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCall) ProtoMessage() {}

func (x *EndCall) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCall.ProtoReflect.Descriptor instead.
func (*EndCall) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{20}
}

func (x *EndCall) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ControlEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CallId   string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	SenderId string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlEvent_Command
	//	*ControlEvent_Gyro
	//	*ControlEvent_Ack
	//	*ControlEvent_State
	Payload       isControlEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEvent) Reset() {
	*x = ControlEvent{}
	mi := &file_xeniq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEvent) ProtoMessage() {}

func (x *ControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEvent.ProtoReflect.Descriptor instead.
func (*ControlEvent) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{21}
}

func (x *ControlEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ControlEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ControlEvent) GetPayload() isControlEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlEvent) GetCommand() *CameraCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControlEvent) GetGyro() *GyroData {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_Gyro); ok {
			return x.Gyro
		}
	}
	return nil
}

func (x *ControlEvent) GetAck() *ControlAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlEvent) GetState() *CameraState {
	if x != nil {
		if x, ok := x.Payload.(*ControlEvent_State); ok {
			return x.State
		}
	}
	return nil
}

type isControlEvent_Payload interface {
	isControlEvent_Payload()
}

type ControlEvent_Command struct {
	Command *CameraCommand `protobuf:"bytes,3,opt,name=command,proto3,oneof"` // Legacy command-based control
}

type ControlEvent_Gyro struct {
	Gyro *GyroData `protobuf:"bytes,4,opt,name=gyro,proto3,oneof"` // Gyro orientation updates
}

type ControlEvent_Ack struct {
	Ack *ControlAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type ControlEvent_State struct {
	State *CameraState `protobuf:"bytes,6,opt,name=state,proto3,oneof"` // State-based camera control (preferred)
}

func (*ControlEvent_Command) isControlEvent_Payload() {}

func (*ControlEvent_Gyro) isControlEvent_Payload() {}

func (*ControlEvent_Ack) isControlEvent_Payload() {}

func (*ControlEvent_State) isControlEvent_Payload() {}

// State-based camera control - replaces command flooding
type CameraState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoomLevel     float32                `protobuf:"fixed32,1,opt,name=zoom_level,json=zoomLevel,proto3" json:"zoom_level,omitempty"` // Absolute zoom: 1.0 = normal, up to max (e.g. 6.0)
	AnchorX       float32                `protobuf:"fixed32,2,opt,name=anchor_x,json=anchorX,proto3" json:"anchor_x,omitempty"`       // Normalized 0.0-1.0, zoom anchor X
	AnchorY       float32                `protobuf:"fixed32,3,opt,name=anchor_y,json=anchorY,proto3" json:"anchor_y,omitempty"`       // Normalized 0.0-1.0, zoom anchor Y
	Mode          ControlModeType        `protobuf:"varint,4,opt,name=mode,proto3,enum=xeniq.ControlModeType" json:"mode,omitempty"`  // Current control mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraState) Reset() {
	*x = CameraState{}
	mi := &file_xeniq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraState) ProtoMessage() {}

func (x *CameraState) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraState.ProtoReflect.Descriptor instead.
func (*CameraState) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{22}
}

func (x *CameraState) GetZoomLevel() float32 {
	if x != nil {
		return x.ZoomLevel
	}
	return 0
}

func (x *CameraState) GetAnchorX() float32 {
	if x != nil {
		return x.AnchorX
	}
	return 0
}

func (x *CameraState) GetAnchorY() float32 {
	if x != nil {
		return x.AnchorY
	}
	return 0
}

func (x *CameraState) GetMode() ControlModeType {
	if x != nil {
		return x.Mode
	}
	return ControlModeType_CONTROL_MODE_BUTTON
}

// Legacy command-based control (for backwards compatibility)
type CameraCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=xeniq.CommandType" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraCommand) Reset() {
	*x = CameraCommand{}
	mi := &file_xeniq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraCommand) ProtoMessage() {}

func (x *CameraCommand) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraCommand.ProtoReflect.Descriptor instead.
func (*CameraCommand) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{23}
}

func (x *CameraCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_UNKNOWN
}

func (x *CameraCommand) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GyroData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Roll          float32                `protobuf:"fixed32,4,opt,name=roll,proto3" json:"roll,omitempty"`
	Pitch         float32                `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"` // Normalized -1.0 to +1.0
	Yaw           float32                `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`     // Normalized -1.0 to +1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GyroData) Reset() {
	*x = GyroData{}
	mi := &file_xeniq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GyroData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GyroData) ProtoMessage() {}

func (x *GyroData) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GyroData.ProtoReflect.Descriptor instead.
func (*GyroData) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{24}
}

func (x *GyroData) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GyroData) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GyroData) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *GyroData) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *GyroData) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *GyroData) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type ControlAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	mi := &file_xeniq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_xeniq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_xeniq_proto_rawDescGZIP(), []int{25}
}

func (x *ControlAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ControlAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_xeniq_proto protoreflect.FileDescriptor

const file_xeniq_proto_rawDesc = "" +
	"\n" +
	"\vxeniq.proto\x12\x05xeniq\"\x99\x01\n" +
	"\x17RegisterProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_code\x18\x02 \x01(\tR\fproviderCode\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"s\n" +
	"\x18RegisterProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rprovider_code\x18\x03 \x01(\tR\fproviderCode\"\\\n" +
	"\x16SetAvailabilityRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\"X\n" +
	"\x17SetAvailabilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rprovider_code\x18\x02 \x01(\tR\fproviderCode\"\x16\n" +
	"\x14ListProvidersRequest\"Q\n" +
	"\x15ListProvidersResponse\x128\n" +
	"\tproviders\x18\x01 \x03(\v2\x1a.xeniq.ProviderStatusEventR\tproviders\"4\n" +
	"\rSearchRequest\x12#\n" +
	"\rprovider_code\x18\x01 \x01(\tR\fproviderCode\"\x88\x01\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fis_available\x18\x04 \x01(\bR\visAvailable\"\xd6\x01\n" +
	"\x13ProviderStatusEvent\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_code\x18\x02 \x01(\tR\fproviderCode\x12!\n" +
	"\fis_available\x18\x03 \x01(\bR\visAvailable\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"7\n" +
	"\x14IncomingCallsRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"\x8c\x01\n" +
	"\x11IncomingCallEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\"\xb3\x01\n" +
	"\vCallRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12#\n" +
	"\rprovider_code\x18\x05 \x01(\tR\fproviderCode\"[\n" +
	"\fCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"M\n" +
	"\x11AnswerCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\"M\n" +
	"\x12AnswerCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"f\n" +
	"\x12DeclineCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"/\n" +
	"\x13DeclineCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xef\x01\n" +
	"\x0fConnectionEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12'\n" +
	"\x03ice\x18\x06 \x01(\v2\x13.xeniq.IceCandidateH\x00R\x03ice\x12-\n" +
	"\x03sdp\x18\a \x01(\v2\x19.xeniq.SessionDescriptionH\x00R\x03sdp\x12\"\n" +
	"\x03end\x18\b \x01(\v2\x0e.xeniq.EndCallH\x00R\x03endB\t\n" +
	"\apayload\"n\n" +
	"\fIceCandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12'\n" +
	"\x10sdp_m_line_index\x18\x03 \x01(\x05R\rsdpMLineIndex\":\n" +
	"\x12SessionDescription\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\"!\n" +
	"\aEndCall\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xfb\x01\n" +
	"\fControlEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x120\n" +
	"\acommand\x18\x03 \x01(\v2\x14.xeniq.CameraCommandH\x00R\acommand\x12%\n" +
	"\x04gyro\x18\x04 \x01(\v2\x0f.xeniq.GyroDataH\x00R\x04gyro\x12%\n" +
	"\x03ack\x18\x05 \x01(\v2\x11.xeniq.ControlAckH\x00R\x03ack\x12*\n" +
	"\x05state\x18\x06 \x01(\v2\x12.xeniq.CameraStateH\x00R\x05stateB\t\n" +
	"\apayload\"\x8e\x01\n" +
	"\vCameraState\x12\x1d\n" +
	"\n" +
	"zoom_level\x18\x01 \x01(\x02R\tzoomLevel\x12\x19\n" +
	"\banchor_x\x18\x02 \x01(\x02R\aanchorX\x12\x19\n" +
	"\banchor_y\x18\x03 \x01(\x02R\aanchorY\x12*\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x16.xeniq.ControlModeTypeR\x04mode\"M\n" +
	"\rCameraCommand\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.xeniq.CommandTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"p\n" +
	"\bGyroData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x12\n" +
	"\x04roll\x18\x04 \x01(\x02R\x04roll\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\x12\x10\n" +
	"\x03yaw\x18\x06 \x01(\x02R\x03yaw\"E\n" +
	"\n" +
	"ControlAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess*A\n" +
	"\x0fControlModeType\x12\x17\n" +
	"\x13CONTROL_MODE_BUTTON\x10\x00\x12\x15\n" +
	"\x11CONTROL_MODE_GYRO\x10\x01*\xc2\x01\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vROTATE_LEFT\x10\x01\x12\x10\n" +
	"\fROTATE_RIGHT\x10\x02\x12\x10\n" +
	"\fMOVE_FORWARD\x10\x03\x12\x11\n" +
	"\rMOVE_BACKWARD\x10\x04\x12\x13\n" +
	"\x0fPOINT_TO_OBJECT\x10\x05\x12\v\n" +
	"\aZOOM_IN\x10\x06\x12\f\n" +
	"\bZOOM_OUT\x10\a\x12\b\n" +
	"\x04STOP\x10\b\x12\x14\n" +
	"\x10GYRO_ORIENTATION\x10\t\x12\x0e\n" +
	"\n" +
	"GYRO_RESET\x10\n" +
	"2\xc3\x02\n" +
	"\x0fProviderService\x12S\n" +
	"\x10RegisterProvider\x12\x1e.xeniq.RegisterProviderRequest\x1a\x1f.xeniq.RegisterProviderResponse\x12P\n" +
	"\x0fSetAvailability\x12\x1d.xeniq.SetAvailabilityRequest\x1a\x1e.xeniq.SetAvailabilityResponse\x12J\n" +
	"\rListProviders\x12\x1b.xeniq.ListProvidersRequest\x1a\x1c.xeniq.ListProvidersResponse\x12=\n" +
	"\x0eSearchProvider\x12\x14.xeniq.SearchRequest\x1a\x15.xeniq.SearchResponse2\xe9\x02\n" +
	"\x0eConnectService\x12N\n" +
	"\x13StreamIncomingCalls\x12\x1b.xeniq.IncomingCallsRequest\x1a\x18.xeniq.IncomingCallEvent0\x01\x126\n" +
	"\vRequestCall\x12\x12.xeniq.CallRequest\x1a\x13.xeniq.CallResponse\x12A\n" +
	"\n" +
	"AcceptCall\x12\x18.xeniq.AnswerCallRequest\x1a\x19.xeniq.AnswerCallResponse\x12D\n" +
	"\vDeclineCall\x12\x19.xeniq.DeclineCallRequest\x1a\x1a.xeniq.DeclineCallResponse\x12F\n" +
	"\x10StreamConnection\x12\x16.xeniq.ConnectionEvent\x1a\x16.xeniq.ConnectionEvent(\x010\x012O\n" +
	"\x0eControlService\x12=\n" +
	"\rStreamControl\x12\x13.xeniq.ControlEvent\x1a\x13.xeniq.ControlEvent(\x010\x01B'Z%github.com/neha/xeniqclone/backend/pbb\x06proto3"

var (
	file_xeniq_proto_rawDescOnce sync.Once
	file_xeniq_proto_rawDescData []byte
)

func file_xeniq_proto_rawDescGZIP() []byte {
	file_xeniq_proto_rawDescOnce.Do(func() {
		file_xeniq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xeniq_proto_rawDesc), len(file_xeniq_proto_rawDesc)))
	})
	return file_xeniq_proto_rawDescData
}

var file_xeniq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xeniq_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_xeniq_proto_goTypes = []any{
	(ControlModeType)(0),             // 0: xeniq.ControlModeType
	(CommandType)(0),                 // 1: xeniq.CommandType
	(*RegisterProviderRequest)(nil),  // 2: xeniq.RegisterProviderRequest
	(*RegisterProviderResponse)(nil), // 3: xeniq.RegisterProviderResponse
	(*SetAvailabilityRequest)(nil),   // 4: xeniq.SetAvailabilityRequest
	(*SetAvailabilityResponse)(nil),  // 5: xeniq.SetAvailabilityResponse
	(*ListProvidersRequest)(nil),     // 6: xeniq.ListProvidersRequest
	(*ListProvidersResponse)(nil),    // 7: xeniq.ListProvidersResponse
	(*SearchRequest)(nil),            // 8: xeniq.SearchRequest
	(*SearchResponse)(nil),           // 9: xeniq.SearchResponse
	(*ProviderStatusEvent)(nil),      // 10: xeniq.ProviderStatusEvent
	(*IncomingCallsRequest)(nil),     // 11: xeniq.IncomingCallsRequest
	(*IncomingCallEvent)(nil),        // 12: xeniq.IncomingCallEvent
	(*CallRequest)(nil),              // 13: xeniq.CallRequest
	(*CallResponse)(nil),             // 14: xeniq.CallResponse
	(*AnswerCallRequest)(nil),        // 15: xeniq.AnswerCallRequest
	(*AnswerCallResponse)(nil),       // 16: xeniq.AnswerCallResponse
	(*DeclineCallRequest)(nil),       // 17: xeniq.DeclineCallRequest
	(*DeclineCallResponse)(nil),      // 18: xeniq.DeclineCallResponse
	(*ConnectionEvent)(nil),          // 19: xeniq.ConnectionEvent
	(*IceCandidate)(nil),             // 20: xeniq.IceCandidate
	(*SessionDescription)(nil),       // 21: xeniq.SessionDescription
	(*EndCall)(nil),                  // 22: xeniq.EndCall
	(*ControlEvent)(nil),             // 23: xeniq.ControlEvent
	(*CameraState)(nil),              // 24: xeniq.CameraState
	(*CameraCommand)(nil),            // 25: xeniq.CameraCommand
	(*GyroData)(nil),                 // 26: xeniq.GyroData
	(*ControlAck)(nil),               // 27: xeniq.ControlAck
}
var file_xeniq_proto_depIdxs = []int32{
	10, // 0: xeniq.ListProvidersResponse.providers:type_name -> xeniq.ProviderStatusEvent
	20, // 1: xeniq.ConnectionEvent.ice:type_name -> xeniq.IceCandidate
	21, // 2: xeniq.ConnectionEvent.sdp:type_name -> xeniq.SessionDescription
	22, // 3: xeniq.ConnectionEvent.end:type_name -> xeniq.EndCall
	25, // 4: xeniq.ControlEvent.command:type_name -> xeniq.CameraCommand
	26, // 5: xeniq.ControlEvent.gyro:type_name -> xeniq.GyroData
	27, // 6: xeniq.ControlEvent.ack:type_name -> xeniq.ControlAck
	24, // 7: xeniq.ControlEvent.state:type_name -> xeniq.CameraState
	0,  // 8: xeniq.CameraState.mode:type_name -> xeniq.ControlModeType
	1,  // 9: xeniq.CameraCommand.type:type_name -> xeniq.CommandType
	2,  // 10: xeniq.ProviderService.RegisterProvider:input_type -> xeniq.RegisterProviderRequest
	4,  // 11: xeniq.ProviderService.SetAvailability:input_type -> xeniq.SetAvailabilityRequest
	6,  // 12: xeniq.ProviderService.ListProviders:input_type -> xeniq.ListProvidersRequest
	8,  // 13: xeniq.ProviderService.SearchProvider:input_type -> xeniq.SearchRequest
	11, // 14: xeniq.ConnectService.StreamIncomingCalls:input_type -> xeniq.IncomingCallsRequest
	13, // 15: xeniq.ConnectService.RequestCall:input_type -> xeniq.CallRequest
	15, // 16: xeniq.ConnectService.AcceptCall:input_type -> xeniq.AnswerCallRequest
	17, // 17: xeniq.ConnectService.DeclineCall:input_type -> xeniq.DeclineCallRequest
	19, // 18: xeniq.ConnectService.StreamConnection:input_type -> xeniq.ConnectionEvent
	23, // 19: xeniq.ControlService.StreamControl:input_type -> xeniq.ControlEvent
	3,  // 20: xeniq.ProviderService.RegisterProvider:output_type -> xeniq.RegisterProviderResponse
	5,  // 21: xeniq.ProviderService.SetAvailability:output_type -> xeniq.SetAvailabilityResponse
	7,  // 22: xeniq.ProviderService.ListProviders:output_type -> xeniq.ListProvidersResponse
	9,  // 23: xeniq.ProviderService.SearchProvider:output_type -> xeniq.SearchResponse
	12, // 24: xeniq.ConnectService.StreamIncomingCalls:output_type -> xeniq.IncomingCallEvent
	14, // 25: xeniq.ConnectService.RequestCall:output_type -> xeniq.CallResponse
	16, // 26: xeniq.ConnectService.AcceptCall:output_type -> xeniq.AnswerCallResponse
	18, // 27: xeniq.ConnectService.DeclineCall:output_type -> xeniq.DeclineCallResponse
	19, // 28: xeniq.ConnectService.StreamConnection:output_type -> xeniq.ConnectionEvent
	23, // 29: xeniq.ControlService.StreamControl:output_type -> xeniq.ControlEvent
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xeniq_proto_init() }
func file_xeniq_proto_init() {
	if File_xeniq_proto != nil {
		return
	}
	file_xeniq_proto_msgTypes[17].OneofWrappers = []any{
		(*ConnectionEvent_Ice)(nil),
		(*ConnectionEvent_Sdp)(nil),
		(*ConnectionEvent_End)(nil),
	}
	file_xeniq_proto_msgTypes[21].OneofWrappers = []any{
		(*ControlEvent_Command)(nil),
		(*ControlEvent_Gyro)(nil),
		(*ControlEvent_Ack)(nil),
		(*ControlEvent_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xeniq_proto_rawDesc), len(file_xeniq_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_xeniq_proto_goTypes,
		DependencyIndexes: file_xeniq_proto_depIdxs,
		EnumInfos:         file_xeniq_proto_enumTypes,
		MessageInfos:      file_xeniq_proto_msgTypes,
	}.Build()
	File_xeniq_proto = out.File
	file_xeniq_proto_goTypes = nil
	file_xeniq_proto_depIdxs = nil
}
